export const SUBMITTED_SEARCH = 'SUBMITTED_SEARCH';
export const GET_WEATHERDATA = 'GET_WEATHERDATA';
export const CLICKED_SEARCH = 'CLICKED_SEARCH';
export const FETCH_HIGHLIGHTED_CITY = 'FETCH_HIGHLIGHTED_CITY';
